// Generated by CoffeeScript 1.6.0
(function() {

  describe("Lunch.Services", function() {
    beforeEach(module("Lunch"));
    return describe("getLunchMates", function() {
      LunchMates;      beforeEach(inject(function($injector) {
        var LunchMates;
        return LunchMates = $injector.get('LunchMates');
      }));
      return it("returns something", function() {
        return expect(LunchMates.testFunction()).toBe("test");
      });
    });
  });

}).call(this);
