development:
  adapter: postgresql
  encoding: unicode
  database: lookingtolunch_dev
  pool: 5
  host: localhost
  port: 5432  

test:
  adapter: postgresql
  encoding: unicode
  database: lookingtolunch_test<%= ENV['TEST_ENV_NUMBER'] %>
  pool: 5
  host: localhost
  port: 5432  
